server:
  port: 8081
  servlet:
    context-path: /connect-pdv/pdv/api

spring:
  application:
    name: pdv

  datasource:
    url: jdbc:mysql://localhost:3306/pdv
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    security:
      user:
        name: admin
        password: senha123

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false