server:
  port: 8081
  servlet:
    context-path: /connect-pdv/pdv/api

spring:
  application:
    name: pdv

  credential:
    password: 123

  datasource:
    url: jdbc:mysql://localhost:3306/pdv
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org.springframework.security: DEBUG
